### ISSUE TITLE
[Add Project 🎃] Shuru

### ISSUE THREAD

**Issue by harshdoesdev** [Chirag8023/hacktospot#2]
Name : Shuru
Link : https://github.com/harshdoesdev/shuru

Do project offer any kind of digital or physical swag ? (put "x" in between [ ] brackets)
- [x]  yes
- [ ] no

**Comment by harshdoesdev** [comment]
Swags: 5 (New) contributors (Code and Docs) - [StickerPress stickers](https://www.stickerpress.in/) related to the Rust programming language

**Comment by Chirag8023** [comment]
Thank you Harsh for new new entry,  it will be added to the list in a while ✨

**Comment by Chirag8023** [comment]
Is that 5 stickers on from 1 to any number of pr merged,  right?  5 sticker per person?

**Comment by harshdoesdev** [comment]
Yes, 5 stickers per person.

**Comment by Chirag8023** [comment]
what logo i should use ?

**Comment by Chirag8023** [comment]
I added the project to the list so could see it in a minute, so if there's no logo then it's okay.
just check it and tell it's looking okay, so i can close this issue.

thank you

**Comment by harshdoesdev** [comment]
Please use this logo: https://github.com/harshdoesdev/shuru/blob/main/shuru.svg

Thanks!

**Comment by harshdoesdev** [comment]
Thank you! I see that the logo has been updated. We can close this issue now.

**Comment by harshdoesdev** [comment]
Thank you! I see that the logo has been updated. We can close this issue now.
